# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcLatest < Formula
  desc "Fetch the latest Claude Code changelog entry"
  homepage "https://github.com/arimxyer/cc-latest"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arimxyer/cc-latest/releases/download/v1.0.0/cc-latest_1.0.0_darwin_amd64.tar.gz"
      sha256 "f92daad632f0fb3ebaf28a5f45b92b468dc01fe8d8000a8de93f40459258990a"

      def install
        bin.install "cc-latest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arimxyer/cc-latest/releases/download/v1.0.0/cc-latest_1.0.0_darwin_arm64.tar.gz"
      sha256 "ce48ab2ef214cb8c3b171e8be419fce6f9647e5994518a2de80a8883b9688abf"

      def install
        bin.install "cc-latest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arimxyer/cc-latest/releases/download/v1.0.0/cc-latest_1.0.0_linux_amd64.tar.gz"
      sha256 "9817c5cec2187c0ecbe4231e27c4760bd3f4f905a8cfd34be7c1d0ae4a4e959a"
      def install
        bin.install "cc-latest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arimxyer/cc-latest/releases/download/v1.0.0/cc-latest_1.0.0_linux_arm64.tar.gz"
      sha256 "f1ba11235356705ca5c0d92bce1ecf0fdbf88cab76981aaa238c0a1bd208abac"
      def install
        bin.install "cc-latest"
      end
    end
  end
end
