# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aic < Formula
  desc "AI Coding Agent Changelog Viewer - fetch changelogs for Claude Code, Codex, OpenCode, Gemini CLI, Copilot CLI"
  homepage "https://github.com/arimxyer/aic"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arimxyer/aic/releases/download/v2.0.0/aic_2.0.0_darwin_amd64.tar.gz"
      sha256 "4e80b768e27f0e23c9cdfdf23edbef25988fd88d5f328a1be6e087416d3d6e88"

      def install
        bin.install "aic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arimxyer/aic/releases/download/v2.0.0/aic_2.0.0_darwin_arm64.tar.gz"
      sha256 "92d6cbaa8c4722a5d178d083a3583c0f6db5beb8dcf29dba8dc423da0135b49f"

      def install
        bin.install "aic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arimxyer/aic/releases/download/v2.0.0/aic_2.0.0_linux_amd64.tar.gz"
      sha256 "67af89f08f1bc6a31d4a33e8a0c1ed02bc2acaefa8699052bf3af5875d4301f7"
      def install
        bin.install "aic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arimxyer/aic/releases/download/v2.0.0/aic_2.0.0_linux_arm64.tar.gz"
      sha256 "24e2d8e3b5bb209e6de469ae2ac345bb6d20196530d1331ac2fb3080c3204829"
      def install
        bin.install "aic"
      end
    end
  end
end
