# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aic < Formula
  desc "AI Coding Agent Changelog Viewer - fetch changelogs for Claude Code, Codex, OpenCode, Gemini CLI, Copilot CLI"
  homepage "https://github.com/arimxyer/aic"
  version "2.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arimxyer/aic/releases/download/v2.6.0/aic_2.6.0_darwin_amd64.tar.gz"
      sha256 "dad4560a4801b448ff5d6c16c3e26fc85e1e9dcf44a168a1d660d3c42ff9ef5b"

      def install
        bin.install "aic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arimxyer/aic/releases/download/v2.6.0/aic_2.6.0_darwin_arm64.tar.gz"
      sha256 "442c6352ab705dd83ea5a17ca333ff6b88b790c3aeb83393f6a0a86d179dc6fb"

      def install
        bin.install "aic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arimxyer/aic/releases/download/v2.6.0/aic_2.6.0_linux_amd64.tar.gz"
      sha256 "7563393b936055d33a6e812ea361646b335437dfc37971176b934c50567b680c"
      def install
        bin.install "aic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arimxyer/aic/releases/download/v2.6.0/aic_2.6.0_linux_arm64.tar.gz"
      sha256 "c202d26c448b0df7bc348c9c889d828291bf548d08bb3a75a9059585d85dd5a2"
      def install
        bin.install "aic"
      end
    end
  end
end
