# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcLatest < Formula
  desc "Fetch the latest Claude Code changelog entry"
  homepage "https://github.com/arimxyer/cc-latest"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arimxyer/cc-latest/releases/download/v1.0.1/cc-latest_1.0.1_darwin_amd64.tar.gz"
      sha256 "120bc43d9771723c1a4e546af31e6b81d2e8a648bdfd8d3712a3a2780bc11c12"

      def install
        bin.install "cc-latest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arimxyer/cc-latest/releases/download/v1.0.1/cc-latest_1.0.1_darwin_arm64.tar.gz"
      sha256 "6c06c1933aac45bf16a9dc13fdd7342d595b4ca94ec91bf0050ea91d43b53eb2"

      def install
        bin.install "cc-latest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arimxyer/cc-latest/releases/download/v1.0.1/cc-latest_1.0.1_linux_amd64.tar.gz"
      sha256 "4f34bbb752f41a086e7f6e0690f477dfce128fe2c3ffb2a30a4f90a8b8d17e83"
      def install
        bin.install "cc-latest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arimxyer/cc-latest/releases/download/v1.0.1/cc-latest_1.0.1_linux_arm64.tar.gz"
      sha256 "e386ab8fe922f1497998433f95839c604e40b1b21f42646271b58439207a1792"
      def install
        bin.install "cc-latest"
      end
    end
  end
end
