# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PassCli < Formula
  desc "Secure, cross-platform CLI password and API key manager for developers"
  homepage "https://github.com/arimxyer/pass-cli"
  version "0.17.0"
  license "MIT"

  on_macos do
    url "https://github.com/arimxyer/pass-cli/releases/download/v0.17.0/pass-cli_0.17.0_darwin_all.tar.gz"
    sha256 "c9f3927ccc059f94ac4640595705e1ae37348d2b068725c091fec14c5f41e341"

    def install
      bin.install "pass-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arimxyer/pass-cli/releases/download/v0.17.0/pass-cli_0.17.0_linux_x86_64.tar.gz"
      sha256 "501a00c9d5750d421f81fd4c18476127eeea51b6af001e7f66e6e42cf90e1c4c"
      def install
        bin.install "pass-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arimxyer/pass-cli/releases/download/v0.17.0/pass-cli_0.17.0_linux_arm64.tar.gz"
      sha256 "a7e17d4428e4cb25943e88a8c9f83cc9d02de63fcccb2663e665bb7a341cd632"
      def install
        bin.install "pass-cli"
      end
    end
  end

  def caveats
    <<~EOS
      Pass-CLI: Secure password manager with TUI and CLI interfaces

      First-time users: Run `pass-cli` (no arguments) for guided setup.

      Quick start:
        pass-cli          - Launch interactive TUI
        pass-cli init     - Initialize vault manually
        pass-cli doctor   - Run health checks

      Features:
        • Interactive TUI for visual management
        • Keychain integration: pass-cli keychain enable
        • Usage tracking and audit logging

      Vault location: ~/.pass-cli/vault.enc
      Complete guide: https://github.com/arimxyer/pass-cli/blob/main/docs/GETTING_STARTED.md
    EOS
  end

  test do
    system "#{bin}/pass-cli", "version"
  end
end
