# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PassCli < Formula
  desc "Secure, cross-platform CLI password and API key manager for developers"
  homepage "https://github.com/arimxyer/pass-cli"
  version "0.14.1"
  license "MIT"

  on_macos do
    url "https://github.com/arimxyer/pass-cli/releases/download/v0.14.1/pass-cli_0.14.1_darwin_all.tar.gz"
    sha256 "7a3fe8869e7ba8b72e1d0b7dd931f594061eef602579ac90fa3a4ade39c4fc8b"

    def install
      bin.install "pass-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arimxyer/pass-cli/releases/download/v0.14.1/pass-cli_0.14.1_linux_x86_64.tar.gz"
      sha256 "73c074322c9538335c97ac1be107af477c11729b307b6f5ff6ae2622352c6ae2"
      def install
        bin.install "pass-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arimxyer/pass-cli/releases/download/v0.14.1/pass-cli_0.14.1_linux_arm64.tar.gz"
      sha256 "7750bcdb2e6785151981c3ce930472a7b8739d073648b8b55d22d5f7321b59d0"
      def install
        bin.install "pass-cli"
      end
    end
  end

  def caveats
    <<~EOS
      Pass-CLI: Secure password manager with TUI and CLI interfaces

      First-time users: Run `pass-cli` (no arguments) for guided setup.

      Quick start:
        pass-cli          - Launch interactive TUI
        pass-cli init     - Initialize vault manually
        pass-cli doctor   - Run health checks

      Features:
        • Interactive TUI for visual management
        • Keychain integration: pass-cli keychain enable
        • Usage tracking and audit logging

      Vault location: ~/.pass-cli/vault.enc
      Complete guide: https://github.com/arimxyer/pass-cli/blob/main/docs/GETTING_STARTED.md
    EOS
  end

  test do
    system "#{bin}/pass-cli", "version"
  end
end
