# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PassCli < Formula
  desc "Secure, cross-platform CLI password and API key manager for developers"
  homepage "https://github.com/arimxyer/pass-cli"
  version "0.16.2"
  license "MIT"

  on_macos do
    url "https://github.com/arimxyer/pass-cli/releases/download/v0.16.2/pass-cli_0.16.2_darwin_all.tar.gz"
    sha256 "2f12d94f9976548aa78b00642bc58cdcd08825348bba1b280e03d0ce1aa83f2a"

    def install
      bin.install "pass-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arimxyer/pass-cli/releases/download/v0.16.2/pass-cli_0.16.2_linux_x86_64.tar.gz"
      sha256 "21d9602bca90234172eec87c46d89d5279d34e8a3e155ec22c2a5a9c02595482"
      def install
        bin.install "pass-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arimxyer/pass-cli/releases/download/v0.16.2/pass-cli_0.16.2_linux_arm64.tar.gz"
      sha256 "486795b3dd1f4814995bf54f06a28b94af064d17f120b5f2d997c1f46f529c35"
      def install
        bin.install "pass-cli"
      end
    end
  end

  def caveats
    <<~EOS
      Pass-CLI: Secure password manager with TUI and CLI interfaces

      First-time users: Run `pass-cli` (no arguments) for guided setup.

      Quick start:
        pass-cli          - Launch interactive TUI
        pass-cli init     - Initialize vault manually
        pass-cli doctor   - Run health checks

      Features:
        • Interactive TUI for visual management
        • Keychain integration: pass-cli keychain enable
        • Usage tracking and audit logging

      Vault location: ~/.pass-cli/vault.enc
      Complete guide: https://github.com/arimxyer/pass-cli/blob/main/docs/GETTING_STARTED.md
    EOS
  end

  test do
    system "#{bin}/pass-cli", "version"
  end
end
